// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFOD6qZHXrrNmnTUfNxY0IAfjLWUmKO8',
    appId: '1:739918153272:web:c187c9e2458b64526788cd',
    messagingSenderId: '739918153272',
    projectId: 'busbuddy-a57bd',
    authDomain: 'busbuddy-a57bd.firebaseapp.com',
    storageBucket: 'busbuddy-a57bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYan7uYQxuXC_0DmLjQldBaUDB2UwsoCM',
    appId: '1:739918153272:android:fb128f8856d6d9d86788cd',
    messagingSenderId: '739918153272',
    projectId: 'busbuddy-a57bd',
    storageBucket: 'busbuddy-a57bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBj1WLbe67JGrPDWzndo5ClKom4OwhEc',
    appId: '1:739918153272:ios:3dcc6d64f561c79e6788cd',
    messagingSenderId: '739918153272',
    projectId: 'busbuddy-a57bd',
    storageBucket: 'busbuddy-a57bd.firebasestorage.app',
    androidClientId: '739918153272-69flpi9rnsgevvsrasv322va6c681miv.apps.googleusercontent.com',
    iosClientId: '739918153272-rpd9bn4cudgj6vjat676plshkft96tg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBj1WLbe67JGrPDWzndo5ClKom4OwhEc',
    appId: '1:739918153272:ios:3dcc6d64f561c79e6788cd',
    messagingSenderId: '739918153272',
    projectId: 'busbuddy-a57bd',
    storageBucket: 'busbuddy-a57bd.firebasestorage.app',
    androidClientId: '739918153272-69flpi9rnsgevvsrasv322va6c681miv.apps.googleusercontent.com',
    iosClientId: '739918153272-rpd9bn4cudgj6vjat676plshkft96tg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpFOD6qZHXrrNmnTUfNxY0IAfjLWUmKO8',
    appId: '1:739918153272:web:4230bbcfd31780596788cd',
    messagingSenderId: '739918153272',
    projectId: 'busbuddy-a57bd',
    authDomain: 'busbuddy-a57bd.firebaseapp.com',
    storageBucket: 'busbuddy-a57bd.firebasestorage.app',
  );
}
